export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS";
export const GET_PRODUCT_DETAILS_SUCCESS="GET_PRODUCT_DETAILS_SUCCESS";
export const GET_PRODUCT_DETAILS_FAILED="GET_PRODUCT_DETAILS_FAILED";
export const GET_PRODUCT_DETAILS_RESET="GET_PRODUCT_DETAILS_RESET";